services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: poll-eze-docker
    ports:
      - 3000:3000
      - 5555:5555
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432/postgres
      NODE_ENV: development

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
